options:
  logging: 'CLOUD_LOGGING_ONLY'
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gsutil'
    args: ['rm', 'gs://themoosefamily/index.html']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gsutil'
    args: ['cp', 'index.html', 'gs://themoosefamily']